### ISSUE TITLE
how to extract the lincesing_secrt_key in the modulegarden?

### ISSUE THREAD

**Issue by iCrisper** [TachibanaSuzume/WHMCS_PLUGINS#4]
Hi.

nice to meet php developers in china.
first, I want to ask a question. i want to modify or renew your open source modulegarden license myself, but I cannot get `licensing_scert_key` by extension. can u tell me how to get it? that must be great! :)
i think it's time to get the latest support! 
thank u for the open source code :)

**Comment by TachibanaSuzume** [comment]
Decode the codes from the original plugin using zhaoyuanma.com or something else like that.
And search for licensing_scert_key

**Comment by bubundas17** [comment]
How to decode ioncube 10 PHP 7.0 files?
