### ISSUE TITLE
Module drop-down list not loading

### ISSUE THREAD

**Issue by cankirca** [TachibanaSuzume/WHMCS_PLUGINS#7]
Hello,

Just put all files to the installdir/modules/servers, but module selection drop-down menu is not shown.
I've added 3 custom text field, but when I goto products/add new/module settings, I can see modulesgarden in the dropdown menu, but when I choose it, it didn't show anything.
Why?

Thank you.

**Comment by TachibanaSuzume** [comment]
You have to input the plugins to the dropdown like:

DirectAdminExtended,SolusvmExtendedCloud,CpanelExtended,DirectAdminLicenses,OpenStackVPS,DNSManager2,IPManager,Office365,UnbanCenter,SolusvmExtendedVPS,ProxmoxVPS,ProductLinker,PremiumSupportTickets,PasswordManager,OVHPublicCloud,ProxmoxCloud,ClientAreaDesigner,PleskExtended,RackspaceCloud,VirtuozzoVps,ResellersCenter,SMSCenterForWhmcs,AccountSynchronization,WordpressManager,DiscountCenter,DomainReseller,DigitalOceanDroplets,MultiAutoscale,SolusvmExtendedReseller,Ipmanager2,Advancedbilling,DomainOrdersExtended,ClientareaPopupModule,PaymentGatewayCharges,HostingRenewals,EmojiPicker,Multibrand
